# Netlify configuration for DomiNotes
[build]
  # Set the publish directory to the Flutter web build output
  publish = "build/web"
  # No build command needed - using pre-built files
  command = "echo 'Using pre-built Flutter web files'"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Disable asset optimization to preserve Flutter web files
[build.processing]
  skip_processing = true
