[build]
  # Explicitly disable any build commands
  command = ":"
  # Specify the directory with pre-built files
  publish = "build/web"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
