# Netlify configuration for DomiNotes
[build]
  # No build command needed - using pre-built files
  command = "echo 'Static site deployment'"
  # Explicitly set the publish directory to the root
  publish = "/opt/build/repo"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
